name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "${{ secrets.PROJECT_ID }}"
  REGION: 'europe-west1'
  SERVICE: 'service-test'
  AR_REPO: 'github-actions' # The name of your Artifact Registry repository

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      # ❌ REMOVE THIS STEP
      # - name: 'Docker Auth'
      #   uses: 'docker/login-action@v3'
      #   with:
      #     username: '_json_key'
      #     password: ${{ secrets.GOOGLE_CREDENTIALS }}
      #     registry: '${{ env.REGION }}-docker.pkg.dev'

      # ✅ ADD THIS STEP INSTEAD
      - name: 'Configure Docker'
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{env.AR_REPO}}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - id: 'deploy'
        name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          # <-- FIX 2: Added the AR_REPO variable to match the push path
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.SERVICE }}:${{ github.sha }}'

      - name: 'Show output'
        run: |
          echo ${{ steps.deploy.outputs.url }}